name: CI/CD Pipeline

on:
  push:
    branches: [main]
env:
  AWS_REGION: ap-southeast-1
  AWS_ROLE_ARN: "arn:aws:iam::000000000000:role/GitHubAction-AssumeRoleWithAction" # need to check the correct role ARN
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          cd app
          pip install -r requirements.txt

      - name: Docker Build
        run: |
          cd app
          docker build -t myapp:latest .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and Push Docker Image to ECR
        env:
          ECR_REGISTRY: ${{ secrets.ECR_URL }}
        run: |
          docker tag myapp:latest $ECR_REGISTRY:latest
          docker push $ECR_REGISTRY:latest